project_id = "depsfpodwaprzxffdcks"

[api]
enabled = true

[functions]
  [functions.dhor_book_utils]
    verify_jwt = true
  [functions.student_status]
    verify_jwt = true
  [functions."daily-progress-email"]
    verify_jwt = false
